In [1]:
import numpy as np
#create matrices
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
#addition
C = A+B
#substraction
D = A-B
#multiplication
E = A*B
#matrix multipliction
F = np.dot(A,B) # or A@B
#Transpose
A_transpose=A.T
print("Addition:")
print(C)
print("\nSubstraction:")
print(D)
print("\nElement_wise multiplication:")
print(E)
print("\nMatrix multiplication")
print(F)
print("\nTranspose:")
print(A_transpose)

import numpy as np
# Create a sample matrix
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Perform SVD
U, S, VT = np.linalg.svd(X)
# Choose the number of components to keep (e.g., 2)
n_components = 2
#Reconstruct the matrix with reduced dimensions
X_reconstructed = np.dot(U[:, :n_components], np.dot(np.diag(S[:n_components]),
VT[:n_components, :]))
print("Original Matrix:")
print(X)
print("\nReconstructed Matrix (with reduced dimensions):")
print(X_reconstructed)

Addition:
[[ 6  8]
 [10 12]]

Substraction:
[[-4 -4]
 [-4 -4]]

Element_wise multiplication:
[[ 5 12]
 [21 32]]

Matrix multiplication
[[19 22]
 [43 50]]

Transpose:
[[1 3]
 [2 4]]
Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed Matrix (with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
